# 依存パッケージのインストール
FROM node:23-alpine AS deps
WORKDIR /app
COPY package*.json .
RUN npm ci --only=production

# Build環境
FROM node:23-alpine AS builder
WORKDIR /app
COPY package*.json .
COPY .env.production .env.production
RUN npm ci
COPY . .

RUN npm run build

# 実行環境
FROM node:23-alpine

WORKDIR /app
ENV NODE_ENV production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package.json ./package.json
COPY --from=deps /app/node_modules ./node_modules

# 非特権ユーザーを作成
RUN addgroup -S nonroot && adduser -S nonroot -G nonroot
RUN chown -R nonroot:nonroot /app

# 非特権ユーザーに切り替え
USER nonroot

EXPOSE 3000

CMD [ "npm", "run", "start" ]
