# 依存パッケージのインストール
FROM node:23-alpine AS deps
WORKDIR /app
COPY package*.json .
RUN npm ci --only=production

# Build環境
FROM node:23-alpine AS builder
WORKDIR /app
COPY package*.json .
COPY .env.production .env.production
ARG CACHE_BUST=1
RUN npm ci
COPY . .

ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_BASE_URL_WS
ENV NEXT_PUBLIC_BASE_URL $NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL_WS $NEXT_PUBLIC_BASE_URL_WS

RUN npm run build

# 実行環境
FROM node:23-alpine

WORKDIR /app
ENV NODE_ENV production

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nonroot:nonroot /app/.next ./.next
COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# 非特権ユーザーを作成
RUN addgroup -S nonroot && adduser -S nonroot -G nonroot
RUN chown -R nonroot:nonroot /app

# 非特権ユーザーに切り替え
USER nonroot

EXPOSE 3000

CMD [ "node_modules/.bin/next", "start" ]
