import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <Head>
        <title>もんたGPT</title>
        <meta name="description" content="Googleでログインするページ" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body className="text-gray-600 bg-gray-50">{children}</body>
    </html>
  );
}
