version: "3.9"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monta-gpt
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7.4.0-alpine3.20
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data

  # migrate:
  #   container_name: migrate
  #   build:
  #     context: ./backend/app/db
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     PYTHONPATH: /app
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_NAME: monta-gpt
  #     POSTGRES_URL: "postgresql://postgres:password@postgres:5432/monta-gpt"
  #   entrypoint: ["sh", "-c", "alembic upgrade head"]

volumes:
  postgres-data:
  redis-data:
