# 開発用ステージ
FROM python:3.11-slim AS developer

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    wget=1.21.3-1+b2 \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

# ビルド用ステージ
FROM python:3.11-slim AS builder
WORKDIR /app

COPY ./app/requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

# 最終用ステージ
FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY --from=builder /app/ .

ENV PYTHONPATH=/usr/local/lib/python3.11/site-packages

RUN useradd -m appuser
RUN chown -R appuser:appuser /app

EXPOSE 8000

USER appuser

CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]