apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monta-gpt

configMapGenerator:
  - name: frontend-config
    literals:
      - NEXT_PUBLIC_BASE_URL=http://35.201.101.249/api/v1/
      - NEXT_PUBLIC_BASE_URL_WS=ws://35.201.101.249/api/v2/
  - name: backend-config
    literals:
      - GOOGLE_REDIRECT_URI=http://35.201.101.249/api/v1/auth/google/callback
      - ENV=prd
      - ALLOW_ORIGIN=http://35.201.101.249,ws://35.201.101.249
      - DEFAULT_SESSION_EXPIRATION_DAY=7
      - DOMAIN=http://35.201.101.249

resources:
  - base/deployments/backend.yaml
  - base/deployments/frontend.yaml
  - base/jobs/migration.yaml
  - base/services/backend.yaml
  - base/services/frontend.yaml
  - base/ingress/ingress.yaml
  - base/config/backend-secret.yaml
