apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: monta-gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: asia-northeast1-docker.pkg.dev/monta-gpt/monta-gpt/frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: frontend-config
